### ISSUE TITLE
idea: rename package to tailwindcss-wp-global-styles

### ISSUE THREAD

**Issue by justlevine** [natac13/tailwindcss-wp-global-styles#1]
The application of this library is _any_ WP theme (headless or otherwise) that wants to use the generated global stylesheet with TailwindCSS, and uses nothing intrinsic to FaustJS.

Changing the name will get more eyes/users on this lib.

**Comment by natac13** [comment]
tailwindcss-wp-theme?

**Comment by justlevine** [comment]
I think that implies that this package is a _theme_, and not a bridge between a global stylesheet and tw classes, but honestly _however_ you drop faust is good.

**Comment by natac13** [comment]
Do you have a suggestion?

**Comment by justlevine** [comment]
not beyond ` tailwindcss-wp-global-styles`

**Comment by natac13** [comment]
Done
